// <auto-generated>
// Generated by Input Action Map Context Generator. Do not edit manually —
// re-run the generator if the Action Map changes.
// </auto-generated>
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.InputSystem;
using InputSO;
using Zlipacket.Core.Input;

namespace InputSO
{
    [CreateAssetMenu(menuName = "Zlipacket/Input/Action Maps/Player", fileName = "PlayerMapContext")]
    public class PlayerMapContext : InputMapContext
    {
        public event UnityAction<InputAction.CallbackContext> OnMove;
        public event UnityAction<InputAction.CallbackContext> OnLook;
        public event UnityAction<InputAction.CallbackContext> OnPrimary;
        public event UnityAction<InputAction.CallbackContext> OnSecondary;
        public event UnityAction<InputAction.CallbackContext> OnSpace;

        public override string ActionMapName => "Player";

        protected override void BindActions()
        {
            Subscribe("Move", ctx => OnMove?.Invoke(ctx));
            Subscribe("Look", ctx => OnLook?.Invoke(ctx));
            Subscribe("Primary", ctx => OnPrimary?.Invoke(ctx));
            Subscribe("Secondary", ctx => OnSecondary?.Invoke(ctx));
            Subscribe("Space", ctx => OnSpace?.Invoke(ctx));
        }
    }
}
