// <auto-generated>
// Generated by Input Action Map Context Generator. Do not edit manually —
// re-run the generator if the Action Map changes.
// </auto-generated>
using UnityEngine;
using UnityEngine.Events;
using UnityEngine.InputSystem;
using InputSO;
using Zlipacket.Core.Input;

namespace InputSO
{
    [CreateAssetMenu(menuName = "Zlipacket/Input/Action Maps/UI", fileName = "UIMapContext")]
    public class UIMapContext : InputMapContext
    {
        public event UnityAction<InputAction.CallbackContext> OnNavigate;
        public event UnityAction<InputAction.CallbackContext> OnSubmit;
        public event UnityAction<InputAction.CallbackContext> OnCancel;
        public event UnityAction<InputAction.CallbackContext> OnPoint;
        public event UnityAction<InputAction.CallbackContext> OnClick;
        public event UnityAction<InputAction.CallbackContext> OnScrollWheel;
        public event UnityAction<InputAction.CallbackContext> OnMiddleClick;
        public event UnityAction<InputAction.CallbackContext> OnRightClick;
        public event UnityAction<InputAction.CallbackContext> OnTrackedDevicePosition;
        public event UnityAction<InputAction.CallbackContext> OnTrackedDeviceOrientation;

        public override string ActionMapName => "UI";

        protected override void BindActions()
        {
            Subscribe("Navigate", ctx => OnNavigate?.Invoke(ctx));
            Subscribe("Submit", ctx => OnSubmit?.Invoke(ctx));
            Subscribe("Cancel", ctx => OnCancel?.Invoke(ctx));
            Subscribe("Point", ctx => OnPoint?.Invoke(ctx));
            Subscribe("Click", ctx => OnClick?.Invoke(ctx));
            Subscribe("ScrollWheel", ctx => OnScrollWheel?.Invoke(ctx));
            Subscribe("MiddleClick", ctx => OnMiddleClick?.Invoke(ctx));
            Subscribe("RightClick", ctx => OnRightClick?.Invoke(ctx));
            Subscribe("TrackedDevicePosition", ctx => OnTrackedDevicePosition?.Invoke(ctx));
            Subscribe("TrackedDeviceOrientation", ctx => OnTrackedDeviceOrientation?.Invoke(ctx));
        }
    }
}
