using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using UnityEngine.InputSystem;

namespace Zlipacket.Core.Input.Editor
{
    public class MapContextGeneratorWindow : EditorWindow
    {
        private InputActionAsset inputActionAsset;
        private string outputFolder = "Assets/Zlipacket/Core/Input/Map";
        private string namespaceName = "InputSO";
 
        [MenuItem("Tools/Input System/Action Map SO Generator")]
        public static void ShowWindow()
        {
            var window = GetWindow<MapContextGeneratorWindow>("Input Action Map Context Generator");
            window.minSize = new Vector2(420, 200);
        }
 
        private void OnGUI()
        {
            GUILayout.Label("Input Action Map -> ScriptableObject Generator", EditorStyles.boldLabel);
            EditorGUILayout.Space();
 
            inputActionAsset = (InputActionAsset)EditorGUILayout.ObjectField(
                "Input Action Asset", inputActionAsset, typeof(InputActionAsset), false);
 
            namespaceName = EditorGUILayout.TextField("Namespace", namespaceName);
            outputFolder = EditorGUILayout.TextField("Output Folder", outputFolder);
 
            EditorGUILayout.Space();
 
            if (inputActionAsset != null)
            {
                EditorGUILayout.HelpBox(
                    $"Found {inputActionAsset.actionMaps.Count} action map(s). " +
                    "One script will be generated per map.", MessageType.Info);
            }
 
            using (new EditorGUI.DisabledScope(inputActionAsset == null))
            {
                if (GUILayout.Button("Generate Scripts", GUILayout.Height(30)))
                {
                    Generate();
                }
            }
        }
 
        private void Generate()
        {
            if (!Directory.Exists(outputFolder))
                Directory.CreateDirectory(outputFolder);
 
            int count = 0;
            foreach (var map in inputActionAsset.actionMaps)
            {
                string className = SanitizeName(map.name) + "MapContext";
                string filePath = Path.Combine(outputFolder, className + ".cs");
                string code = GenerateMapClass(map, className);
                File.WriteAllText(filePath, code);
                count++;
            }
 
            AssetDatabase.Refresh();
            EditorUtility.DisplayDialog(
                "Generation Complete",
                $"Generated {count} ScriptableObject script(s) at:\n{outputFolder}\n\n" +
                "After Unity recompiles, use Assets > Create > Input > Action Maps > <MapName> " +
                "to create the actual SO assets.",
                "OK");
        }
 
        private string GenerateMapClass(InputActionMap map, string className)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated>");
            sb.AppendLine("// Generated by Input Action Map Context Generator. Do not edit manually —");
            sb.AppendLine("// re-run the generator if the Action Map changes.");
            sb.AppendLine("// </auto-generated>");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Events;");
            sb.AppendLine("using UnityEngine.InputSystem;");
            sb.AppendLine("using InputSO;");
            sb.AppendLine("using Zlipacket.Core.Input;");
            sb.AppendLine();
            sb.AppendLine($"namespace {namespaceName}");
            sb.AppendLine("{");
            sb.AppendLine($"    [CreateAssetMenu(menuName = \"Zlipacket/Input/Action Maps/{map.name}\", fileName = \"{className}\")]");
            sb.AppendLine($"    public class {className} : InputMapContext");
            sb.AppendLine("    {");
 
            foreach (var action in map.actions)
            {
                string eventName = "On" + SanitizeName(action.name);
                sb.AppendLine($"        public event UnityAction<InputAction.CallbackContext> {eventName};");
            }
 
            sb.AppendLine();
            sb.AppendLine($"        public override string ActionMapName => \"{map.name}\";");
            sb.AppendLine();
            sb.AppendLine("        protected override void BindActions()");
            sb.AppendLine("        {");
 
            foreach (var action in map.actions)
            {
                string eventName = "On" + SanitizeName(action.name);
                sb.AppendLine($"            Subscribe(\"{action.name}\", ctx => {eventName}?.Invoke(ctx));");
            }
 
            sb.AppendLine("        }");
            sb.AppendLine("    }");
            sb.AppendLine("}");
 
            return sb.ToString();
        }
 
        private string SanitizeName(string raw)
        {
            var sb = new StringBuilder();
            bool nextUpper = true;
            foreach (char c in raw)
            {
                if (!char.IsLetterOrDigit(c))
                {
                    nextUpper = true;
                    continue;
                }
                sb.Append(nextUpper ? char.ToUpper(c) : c);
                nextUpper = false;
            }
            return sb.Length > 0 ? sb.ToString() : "Unnamed";
        }
    }
}
